#
#Sun Mar 29 10:18:11 CDT 2026
addition_overlay_b=255
addition_overlay_colour_change=false
addition_overlay_g=96
addition_overlay_r=72
battle_ui_b=159
battle_ui_colour_change=false
battle_ui_g=41
battle_ui_r=0
combat_stage=false
combat_stage_id=0
counter_overlay_b=32
counter_overlay_g=96
counter_overlay_r=216
game_speed_multiplier=1
low_memory_unpacker=false
window_height=720
window_width=960
